### ISSUE TITLE
[development] Need an alternative to CMake!

### ISSUE THREAD

**Issue by DeathHammer000** [SuperV1234/SSVOpenHexagon#113]
I want to build and mod the game for myself, but CMake has been giving me countless errors - and whenever I try to fix them, more just keep on coming up. I need an alternative make utility, as CMake just won't work on my system! Even after two weeks of trying, I just cannot build the game...

**Comment by diggit** [comment]
cmake is pretty standard thing. Rather than finding workaround, you should fix it. What system do you have. What errors do you get? Do you have problems with different software using cmake to build?

**Comment by DeathHammer000** [comment]
I'm on Windows 8.1 and am getting errors with variables. It cannot find my compilers (even though I have MinGW installed at the default location) and also cannot find the Lua directory - yet I have followed all of the instructions. I suspect that the error is SSVCMake and not CMake.

**Comment by SuperV1234** [comment]
Getting CMake to work correctly on Windows can be painful at times. That's why I created [build-win-new.sh](https://github.com/SuperV1234/SSVOpenHexagon/blob/master/build-win-new.sh).

You need to run it using bash on Windows (you can easily find bash for Windows online).

It's been a while since I compiled OH on Windows, so it may not work.

**Comment by DeathHammer000** [comment]
Okay, but now it cannot find the Lua dll (even though it can find the includes!).
