### ISSUE TITLE
No ./build-repository-oh.sh

### ISSUE THREAD

**Issue by lithiumjs** [SuperV1234/SSVOpenHexagon#151]
There's no ./build-repository-oh.sh in the repository, only ./build-repository-rel.sh

How to use it?

P.S. I'm using Manjaro Linux

**Comment by SuperV1234** [comment]
Sorry, the README is outdated. You should be able to simply follow the usual CMake workflow after cloning:

```
./init-repository.sh
mkdir build
cd build
cmake ..
make -j8
```

**Comment by bmwalters** [comment]
[I created an Arch PKGBUILD for OpenHexagon!](https://gist.github.com/bmwalters/4506967a306c5c3945b37b69dffab67e) It's not in the AUR yet, but you can install it by downloading the file and running `makepkg` then `pacman -U <resulting tarball>`. It's currently a bit abnormal due to the fact that assets need to be next to the binary, but that's something that can be improved later.

**Comment by SuperV1234** [comment]
Thanks @bmwalters! I have not tested it yet, but will soon. Do I need to take any action to make this AUR-ready?

**Comment by Zly-u** [comment]
Fixed with the new way of building the repo.
