### ISSUE TITLE
[Could Have] - Clean up root folder clutter in _RELEASE

### ISSUE THREAD

**Issue by AlphaPromethium** [SuperV1234/SSVOpenHexagon#186]
As someone who is thinking on making a level pack, I feel like there are too much game files alongside the custom config overrides batch files in the root folder. Potential new level pack developers may get lost and confused on where to start and new players may not realise they can run these config overrides for better performance.

I believe all game files should be stored in their own folder. As for the config override batch files, I think they are fine staying in the root folder but maybe nice to have them stored in `ConfigOverrides` alongside their JSON configuration.

A/C:
1. All game files (DLL's, JSON's [in root], LIB's, SO's) should be stored in their own folder.
2. [Optional] All config override scripts should be stored inside the `ConfigOverrides` folder alongside their JSON configuration.

**_Priority: Could Have._**

**Comment by Morxemplum** [comment]
At this point, since this is now released on Steam, most people shouldn't have to worry about this being a problem, besides pack developers and people who decide to compile the game themselves. Even if it is a little bit messy, it's still trivial to navigate through. I'm going to be closing this because it's not really become an issue anymore.
