### ISSUE TITLE
Menu items overlapping in the "resolution" menu

### ISSUE THREAD

**Issue by IvoryDuke** [SuperV1234/SSVOpenHexagon#228]
Not sure if this issue has already been fixed (if that is the case I apologize for this redundant issue post) but in the 2.0RC2(win) build I downloaded from the website the "go windowed" option overlaps the title of the menu "resolution"
![Capture](https://user-images.githubusercontent.com/55557854/87862740-a2dbbe00-c953-11ea-819c-13f9f25a73e3.PNG)
I have been experiencing issues building on Windows so I could not try work on a fix myself, but I was trying to add an "" text option in MenuGame.cpp to move down the three options in the right column.
Of course I do not know if this is the ideal solution but I thought I'd mention it.

**Comment by Morxemplum** [comment]
I see what you are saying. Thank you for pointing out the issue 
![image](https://user-images.githubusercontent.com/44561540/87866861-7ddb5100-c93b-11ea-8dfb-d36804506d1e.png)

As of right now, we are thinking about redesigning the menu completely, so there is a good chance that this is not a high priority issue to solve because this menu won't stay forever.

**Comment by IvoryDuke** [comment]
I see.
It is really not a big issue really considering that the functionality of the "go windowed" option is not broken, but it did stand out since all other submenus do not suffer from a similar issue.
Looking forward to the redesigned menus!
