### ISSUE TITLE
[Could Have] - More simplified and customizable walls

### ISSUE THREAD

**Issue by Zly-u** [SuperV1234/SSVOpenHexagon#262]
Basically make walls to return their reference so people will be able to change their properties as they please.
for example:
```lua
local wall = w_wall(side, speed, ...) -- you can provide basic arguments into the function 
--first way of doing it:
wall:setAcceleration(val):setColor(255,255,255,255) -- and so on
--and another(through a dot or column, idk, deppends on the idea later):
wall.setAcceleration(val)
wall.setColor(255,255,255,255)
wall.setAngleOffset(0-360)
wall.setCurviture(0-360)
--and etc
```
So in this way, the wall's functions are more compact and more flexible in usage, I believe.
Just giving the main idea for it.

Ofc you can make basic functions for walls to work with and make a module that simplifies their usage or something.

**Comment by Morxemplum** [comment]
At this point you are just essentially making an abridgement of the custom walls system. Not the worst idea, but how would you pull off the OOP abstraction in the C++ code?

**Comment by Zly-u** [comment]
There probably is a way to do that or just make an OOP abstaction for standard wall functions as you would do thatfor custom walls I guess.
It's still not impossible to do anyway and would be nice to have at very least and will grant more control over le walls.

**Comment by Zly-u** [comment]
If you take for example Love2D engine it returns objects when you create specific elements in the code and can apply a different kinds of methods to them, so yes it is possible in C++ somehow and don't ask me how to do it since I never touched Lua C API.

**Comment by Morxemplum** [comment]
Re-evaluating this now, I don't think this needs to be a native feature. This is 100% doable with a Lua library, perhaps a dependency can be uploaded on the workshop that can accomplish these features (considering that dependencies are now a thing in 2.0.4, someone could simplify the custom wall workflow and accomplish this). 

I'm going to close this issue. Standard walls should remain standard walls because they provide a nice first step to people who don't know how to program. Custom walls are where you'll get a lot more control, but you'll need more programming experience before you can fully understand and control them.
