### ISSUE TITLE
Repair, review and optimize build scripts.

### ISSUE THREAD

**Issue by skrzyp** [SuperV1234/SSVOpenHexagon#87]
Please, review your build system for this project, test it on more configurations and **make it possibe to compile it without any problems on any other machine than your workstation**.

**Comment by lukeadams** [comment]
For dependencies, I suggest that we use some sort of package manager. Instead of a shell script that clones depends (requiring us to manually take care of building, etc), a package manager will take care of making them available for building and linking. I found [cpm](https://github.com/iauns/cpm), which looks promising.
`
  CPM_AddModule("aabb"
    GIT_REPOSITORY "https://github.com/iauns/cpm-glm-aabb"
    GIT_TAG "1.0.2")
`
The ability to link a Github repo as a dependency in a Cmake file like that seems awesome ;)

**Comment by Morxemplum** [comment]
The building process has been entirely redone on June 16th, 2020. If you want to expand on these build instructions for other Linux distributions (we currently have Windows and Arch Linux at the moment. We'd appreciate Debian and MacOS), any contribution is welcome (or open up a separate issue for issues building). Closing this.
