### ISSUE TITLE
"Endurance" mode

### ISSUE THREAD

**Issue by SuperV1234** [SuperV1234/SSVOpenHexagon#91]
I was wondering if scripts can be hot-swapped during gameplay - maybe an "endurance mode" would be possible, where every 30-45 seconds the current script gets randomly changed to another from the same pack.

**Comment by Morxemplum** [comment]
Exschwasion beat you to that, with his weird mashup levels in his packs. This is completely doable in Lua and doesn't need to be a built-in feature. Closing.

**Comment by SuperV1234** [comment]
Are the mashup levels hardcoded? I was thinking of something that allows you to create a "playlist" of existing levels, so that you do not have to hardcode them in a single lua file.

**Comment by Morxemplum** [comment]
I don't know what you mean by "hardcoded" because they don't tamper with the source code. What I mean is they code a separate level where they take the rest of the levels from the pack and mash them up all into one, and it follow the description that you've given here. Exschwasion was the first to start this trend (or if not, he popularized it), which was followed by many pack developers down the line making their own "endurance" levels.

Hard coding this concept into the game may work if this were to actually be presented on an arcade machine, but for a PC game I don't really see a purpose, that's why I originally closed it. If you want to open it back up feel free to.
